spring.application.name=auth-client
server.port=5050

server.servlet.session.cookie.name=CLIENT_SESSION

spring.security.oauth2.client.registration.web-client.client-id=web-client
spring.security.oauth2.client.registration.web-client.client-secret=secret
spring.security.oauth2.client.registration.web-client.scope=read
spring.security.oauth2.client.registration.web-client.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.web-client.redirect-uri="{baseUrl}/login/oauth2/code/{registrationId}"

spring.security.oauth2.client.provider.web-client.authorization-uri=http://localhost:9090/oauth2/authorize
spring.security.oauth2.client.provider.web-client.token-uri=http://localhost:9090/oauth2/token
spring.security.oauth2.client.provider.web-client.user-info-uri=http://localhost:9090/userinfo
spring.security.oauth2.client.provider.web-client.user-name-attribute=sub

RESOURCE_SERVER_URL=http://localhost:5200/

logging.level.org.springframework.security=DEBUG